#include "load_save_png.hpp"
#include "PPU466.hpp"
#include <array>
#include <iostream>
#include <stdexcept>
#include <vector>
#include <fstream>

using Palette = std::array<glm::u8vec4, 4>;

const glm::u8vec4 transparent =
    glm::u8vec4(255, 255, 255, 0);

//Everytime we change the sprites'color, we need to update this palettes
const std::array<Palette, 3> palettes = {

    // Palette 0: Paddle
    Palette{
        transparent,
        glm::u8vec4(39, 39, 39, 255),
        glm::u8vec4(22, 189, 159, 255),
        glm::u8vec4(42, 242, 255, 255)
    },

    // Palette 1: Ball
    Palette{
        transparent,
        glm::u8vec4(39, 39, 39, 255),
        glm::u8vec4(255, 215, 77, 255),
        glm::u8vec4(255, 215, 77, 255)
    },

    // Palette 2: Brick
    Palette{
        transparent,
        glm::u8vec4(0, 0, 0, 255),
        glm::u8vec4(157, 88, 54, 255),
        glm::u8vec4(157, 88, 54, 255)
    }
};

const std::array<uint8_t, 4> tile_palettes = {
    0, // empty
    0, // paddle
    1, // ball
    2  // brick
};

uint8_t get_palette_index(glm::u8vec4 const &pixel, Palette const &palette) 
{
    for (uint8_t i = 0; i < palette.size(); ++i) {
        if (pixel == palette[i]) {
            return i;
        }
    }

    throw std::runtime_error(
        "Pixel color not found in palette."
    );
}

int main() {
    glm::uvec2 size;
    std::vector<glm::u8vec4> data;
    std::array<PPU466::Tile, 4> tiles;

    load_png(
        "sprites/sprites.png",
        &size,
        &data,
        LowerLeftOrigin
    );

    // Extract tiles from the loaded sprite data
    for (uint32_t tile_x = 0; tile_x < 4; ++tile_x) {

        for (uint32_t y = 0; y < 8; ++y) {

            uint8_t row_bit0 = 0;
            uint8_t row_bit1 = 0;

            for (uint32_t x = 0; x < 8; ++x) {

                glm::u8vec4 const &pixel =
                    data[y * size.x + tile_x * 8 + x];

                uint8_t palette_index = tile_palettes[tile_x];

                uint8_t index = get_palette_index(
                    pixel,
                    palettes[palette_index]
                );

                uint8_t bit0 = index & 1;
                uint8_t bit1 = (index >> 1) & 1;

                row_bit0 |= bit0 << x;
                row_bit1 |= bit1 << x;
            }

            tiles[tile_x].bit0[y] = row_bit0;
            tiles[tile_x].bit1[y] = row_bit1;
        }
    }

    // Generate the assets header file, including tiles and palettes
    std::ofstream out("generated/assets.hpp");

    if (!out) {
        throw std::runtime_error(
            "Could not open generated/assets.hpp for writing."
        );
    }

    out << "#pragma once\n";
    out << "\n";
    out << "// Generated by asset_converter.cpp\n";
    out << "#include \"PPU466.hpp\"\n";
    out << "\n";
    out << "namespace Assets {\n";
    out << "\n";

    const std::array<std::string, 4> names = {
        "empty",
        "paddle",
        "ball",
        "brick"
    };

    for (uint32_t tile = 0; tile < 4; ++tile) {

        out << "const PPU466::Tile "
            << names[tile]
            << " = {\n";

        //bit0
        out << "    {";
        for (uint32_t y = 0; y < 8; ++y) {
            if (y != 0) {
                out << ", ";
            }
            out << static_cast<int>(tiles[tile].bit0[y]);
        }
        out << "},\n";

        //bit1
        out << "    {";
        for (uint32_t y = 0; y < 8; ++y) {
            if (y != 0) {
                out << ", ";
            }
            out << static_cast<int>(tiles[tile].bit1[y]);
        }
        out << "}\n";
        out << "};\n\n";
    }

    const std::array<std::string, 3> palette_names = {
    "paddle_palette",
    "ball_palette",
    "brick_palette"
    };

    for (uint32_t p = 0; p < 3; ++p) {

        out << "const PPU466::Palette "
            << palette_names[p]
            << " = {\n";

        for (uint32_t i = 0; i < 4; ++i) {

            glm::u8vec4 const &color = palettes[p][i];

            out << "    glm::u8vec4("
                << static_cast<int>(color.r) << ", "
                << static_cast<int>(color.g) << ", "
                << static_cast<int>(color.b) << ", "
                << static_cast<int>(color.a) << ")";

            if (i != 3) {
                out << ",";
            }

            out << "\n";
        }

        out << "};\n\n";
    }

    out << "} // namespace Assets\n";

    out.close();

    std::cout
        << "Generated generated/assets.hpp"
        << std::endl;

    return 0;
}